In [2]:
import pandas as pd

df_csv= pd.read_csv("train.csv")
df_json = pd.read_json("data.json")

display(df_csv.head(5))
print("CSV: filas, columnas:", df_csv.shape)

display(df_json.head(5))
print("JSON: filas, columnas:", df_json.shape)

df_csv.info()
df_json.info()

,Id,Title,Body,Tags,CreationDate,Y
0,34552656,Java: Repeat Task Every Random Seconds,<p>I'm already familiar with repeating tasks e...,<java><repeat>,2016-01-01 00:21:59,LQ_CLOSE
1,34553034,Why are Java Optionals immutable?,<p>I'd like to understand why Java 8 Optionals...,<java><optional>,2016-01-01 02:03:20,HQ
2,34553174,Text Overlay Image with Darkened Opacity React...,<p>I am attempting to overlay a title over an ...,<javascript><image><overlay><react-native><opa...,2016-01-01 02:48:24,HQ
3,34553318,Why ternary operator in swift is so picky?,"<p>The question is very simple, but I just cou...",<swift><operators><whitespace><ternary-operato...,2016-01-01 03:30:17,HQ
4,34553755,hide/show fab with scale animation,<p>I'm using custom floatingactionmenu. I need...,<android><material-design><floating-action-but...,2016-01-01 05:21:48,HQ

CSV: filas, columnas: (45000, 6)

,id,title,description,url,author,authorUsername,tags,commentsCount,reactionsCount,readingTimeMinutes,coverImage,publishedAt,scrapedAt
0,3666204,4 Tiny Mistakes That Secretly Destroy App Perf...,"Ok, I’m back from my short vacation and return...",https://dev.to/sylwia-lask/4-tiny-mistakes-tha...,Sylwia Laskowska,sylwia-lask,"[javascript, angular, react, frontend]",25,35,6,https://media2.dev.to/dynamic/image/width=1000...,2026-05-14T06:04:15Z,2026-05-14T20:33:59.531Z
1,3661749,React is Overkill: Why Python + HTMX is Domina...,Last year I spent forty minutes setting up a R...,https://dev.to/syedahmershah/react-is-overkill...,Syed Ahmer Shah,syedahmershah,"[python, react, javascript, discuss]",66,155,8,https://media2.dev.to/dynamic/image/width=1000...,2026-05-13T09:28:52Z,2026-05-14T20:33:59.600Z
2,3665653,"onclick is great, actually",A few thoughts on `onclick` and how my opinion...,https://dev.to/darkwiiplayer/onclick-is-great-...,𒎏Wii 🏳️‍⚧️,darkwiiplayer,"[javascript, html]",2,15,2,None,2026-05-13T19:10:34Z,2026-05-14T20:33:59.639Z
3,3671251,HTMX or React? Why I chose a Third Way,If you've been following web development news ...,https://dev.to/0x1/htmx-or-react-why-i-chose-a...,Kevin 心学,0x1,"[javascript, purescript, htmx, react]",0,0,4,https://media2.dev.to/dynamic/image/width=1000...,2026-05-14T18:06:54Z,2026-05-14T20:33:59.686Z
4,3670718,How I rebuilt my SaaS landing page in 6 weeks:...,How I rebuilt my SaaS landing page in 6 weeks ...,https://dev.to/zenovay/how-i-rebuilt-my-saas-l...,Zenovay,zenovay,"[showdev, privacy, webdev, javascript]",0,1,3,None,2026-05-14T16:01:32Z,2026-05-14T20:33:59.716Z

JSON: filas, columnas: (50, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            45000 non-null  int64
 1   Title         45000 non-null  object
 2   Body          45000 non-null  object
 3   Tags          45000 non-null  object
 4   CreationDate  45000 non-null  object
 5   Y             45000 non-null  object
dtypes: int64(1), object(5)
memory usage: 2.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  50 non-null     int64
 1   title               50 non-null     object
 2   description         50 non-null     object
 3   url                 50 non-null     object
 4   author              50 non-null     object
 5   authorUsername      50 non-null     object
 6   tags                50 non-null     object
 7   commentsCount       50 non-null     int64
 8   reactionsCount      50 non-null     int64
 9   readingTimeMinutes  50 non-null     int64
 10  coverImage          21 non-null     object
 11  publishedAt         50 non-null     object
 12  scrapedAt           50 non-null     object
dtypes: int64(4), object(9)
memory usage: 5.2+ KB

In [6]:
print("valors nulos por columna:")
print(df_csv.isnull().sum())

print("\nvalors nulos por columna:")
print(df_json.isnull().sum())

valors nulos por columna:
Id              0
Title           0
Body            0
Tags            0
CreationDate    0
Y               0
dtype: int64

valors nulos por columna:
id                     0
title                  0
description            0
url                    0
author                 0
authorUsername         0
tags                   0
commentsCount          0
reactionsCount         0
readingTimeMinutes     0
coverImage            29
publishedAt            0
scrapedAt              0
dtype: int64

In [8]:
#solo compruebo que se hablen de otros lenguajes
df_csv[['Body']].tail(5)

                                                    Body
44995  <p>I am new to this and I am asking for help t...
44996  <p>I am working on learning Python and was won...
44997  <p>It looks like it costs 8 days per month in ...
44998  <p>"I _____ any questions."</p>\n\n<p>I want t...
44999  <p>I'm very new to programming and I'm teachin...